# Generated by Django 5.1.1 on 2024-09-14 17:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='disasteralert',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
        ),
        migrations.AddIndex(
            model_name='alumni',
            index=models.Index(fields=['location'], name='core_alumni_locatio_8f2320_idx'),
        ),
        migrations.AddIndex(
            model_name='disasteralert',
            index=models.Index(fields=['location'], name='core_disast_locatio_398191_idx'),
        ),
    ]
