# Generated by Django 5.1.1 on 2024-09-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_alumni_location_alter_disasteralert_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasteralert',
            name='episode_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='disasteralert',
            name='event_id',
            field=models.CharField(default='NA', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disasteralert',
            name='event_type',
            field=models.CharField(choices=[('TC', 'Tropical Cyclones'), ('EQ', 'Earthquakes'), ('FL', 'Floods'), ('VO', 'Volcanoes'), ('WF', 'Wild Fires'), ('DR', 'Droughts')], default='NA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='disasteralert',
            name='source_format',
            field=models.CharField(default='xml', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='disasteralert',
            unique_together={('event_type', 'event_id', 'episode_id')},
        ),
    ]
