# Generated by Django 5.1.1 on 2024-09-16 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_disasteralert_episode_id_disasteralert_event_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumni',
            options={'ordering': ['name']},
        ),
    ]
